import mongoose from 'mongoose';

const internalPOStatusSchema = new mongoose.Schema({
  internalPONumber: {
    type: String,
    unique: true,
    required: true
  },
  linkedDealId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Deal'
  },
  linkedDealRequestId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'DealRequest'
  },
  vendorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Vendor'
  },
  vendorName: {
    type: String,
    required: true
  },
  approvedCost: {
    type: Number,
    required: true
  },
  costType: {
    type: String,
    enum: ['Trainer', 'Lab', 'Logistics', 'Content', 'Other'],
    required: true
  },
  poStatus: {
    type: String,
    enum: ['Draft', 'Locked', 'Partially Delivered', 'Closed'],
    default: 'Draft'
  },
  autoGeneratedTimestamp: {
    type: Date,
    default: Date.now
  },
  purchaseOrderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'PurchaseOrder'
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

internalPOStatusSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

export default mongoose.model('InternalPOStatus', internalPOStatusSchema);
