import express from 'express';
import InternalPOStatus from '../models/InternalPOStatus.js';
import { authenticate, authorize } from '../middleware/auth.js';

const router = express.Router();

// Get all PO statuses (view by Ops, Finance, Director)
router.get('/', authenticate, authorize('Operations Manager', 'Finance Manager', 'Director'), async (req, res) => {
  try {
    const poStatuses = await InternalPOStatus.find()
      .populate('linkedDealId', 'dealId clientName totalOrderValue')
      .populate('linkedDealRequestId', 'dealId clientName')
      .populate('vendorId', 'vendorName')
      .populate('purchaseOrderId', 'internalPONumber status')
      .sort({ autoGeneratedTimestamp: -1 });
    res.json(poStatuses);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get PO status by ID
router.get('/:id', authenticate, authorize('Operations Manager', 'Finance Manager', 'Director'), async (req, res) => {
  try {
    const poStatus = await InternalPOStatus.findById(req.params.id)
      .populate('linkedDealId', 'dealId clientName totalOrderValue')
      .populate('linkedDealRequestId', 'dealId clientName')
      .populate('vendorId', 'vendorName')
      .populate('purchaseOrderId', 'internalPONumber status');
    if (!poStatus) {
      return res.status(404).json({ error: 'PO status not found' });
    }
    res.json(poStatus);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
